name: 🐞 Bug report
description: Report a reproducible defect
title: "[BUG] "
labels: ["type/bug", "status/ready"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us reproduce and fix it.
        
  - type: input
    id: environment
    attributes:
      label: 🌍 Environment
      description: Where did this bug occur?
      placeholder: "Production / macOS 14 / Chrome 126 / v2.3.1"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of the bug
      placeholder: |
        The dashboard crashes when clicking the "Export" button if no data is selected
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to Dashboard page
        2. Leave all filters empty
        3. Click "Export to CSV" button
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What should happen?
      placeholder: |
        The system should show a warning message "Please select data to export"
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happens?
      placeholder: |
        The page shows a 500 error and becomes unresponsive
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: 📸 Screenshots / Logs
      description: |
        Drag and drop screenshots here or paste error logs.
        Tip: You can paste images directly from clipboard!
      placeholder: |
        ```
        Error: Cannot read property 'length' of undefined
        at exportData (dashboard.js:142:15)
        ```
        
  - type: dropdown
    id: frequency
    attributes:
      label: 🔁 Frequency
      description: How often does this bug occur?
      options:
        - Always (100%)
        - Often (> 50%)
        - Sometimes (10-50%)
        - Rarely (< 10%)
      default: 0
      
  - type: dropdown
    id: severity
    attributes:
      label: 💥 Severity
      description: How severe is this bug?
      options:
        - 🚨 Critical - System unusable
        - 🔥 High - Major feature broken
        - ⚠️  Medium - Minor feature affected
        - 🟢 Low - Cosmetic issue
      default: 2
      
  - type: textarea
    id: workaround
    attributes:
      label: 🔧 Workaround
      description: Is there a temporary workaround?
      placeholder: |
        Users can export by first selecting at least one item
        
  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 Pre-submission Checklist
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
        - label: I can reproduce this bug consistently
          required: true
        - label: This happens in the latest version
          required: true