name: ✨ Feature request
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: ["type/feature", "status/ready"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature! Please fill out the sections below.
        
  - type: textarea
    id: context
    attributes:
      label: 📋 Context & Problem
      description: What user need or business problem should this solve?
      placeholder: |
        e.g., Users cannot reset their password in a single step, causing frustration and support tickets
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        Add a "Forgot Password" link on login page that sends a reset email
    validations:
      required: true
      
  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      description: Bullet-point list of measurable "done" conditions
      placeholder: |
        - [ ] User can reset password in ≤ 2 steps
        - [ ] Confirmation email is sent within 30 seconds
        - [ ] Password reset link expires after 24 hours
        - [ ] Success message shows after password change
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 🤔 Alternatives Considered
      description: What other solutions did you consider?
      placeholder: |
        - SMS verification (too expensive)
        - Security questions (less secure)
        
  - type: dropdown
    id: scope
    attributes:
      label: 🎯 Scope
      description: Which part of the system does this affect?
      multiple: true
      options:
        - backend
        - frontend
        - infra
        - mobile
        - ux
        - db
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 Priority
      description: How important is this feature?
      options:
        - 🚨 Critical (P0)
        - 🔥 High (P1)
        - ⚠️  Medium (P2)
        - 🟢 Low (P3)
      default: 2
      
  - type: input
    id: estimate
    attributes:
      label: 📏 Story Points
      description: Relative size estimate (Fibonacci 1, 2, 3, 5, 8, 13)
      placeholder: "5"
      
  - type: checkboxes
    id: checklist
    attributes:
      label: 📝 Pre-submission Checklist
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
        - label: This aligns with the project's goals
          required: true