name: 📋 Task
description: General task or chore
title: "[TASK] "
labels: ["type/chore", "status/ready"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for general tasks, maintenance work, or chores.
        
  - type: textarea
    id: description
    attributes:
      label: 📝 Task Description
      description: What needs to be done?
      placeholder: |
        Update all dependencies to latest stable versions
    validations:
      required: true
      
  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      description: How do we know when this is done?
      placeholder: |
        - [ ] All dependencies updated
        - [ ] Tests pass
        - [ ] No security vulnerabilities
        - [ ] CHANGELOG updated
    validations:
      required: true
      
  - type: textarea
    id: technical
    attributes:
      label: 🔧 Technical Notes
      description: Implementation details or considerations
      placeholder: |
        - Check breaking changes in React 18
        - Update webpack config for v5
        
  - type: dropdown
    id: scope
    attributes:
      label: 🎯 Scope
      description: Which part of the system does this affect?
      multiple: true
      options:
        - backend
        - frontend
        - infra
        - mobile
        - docs
        - ci/cd
      
  - type: input
    id: estimate
    attributes:
      label: ⏱️ Time Estimate
      description: How long will this take?
      placeholder: "2 hours"